sudo: false
language: scala
scala:
- 2.12.9
jdk:
- openjdk11
before_install:
- git fetch --tags
stages:
- name: test
- name: release
  if: "((branch = master AND type = push) OR (tag IS present)) AND NOT fork"
jobs:
  include:
  - stage: test
    script: sbt test
  - stage: release
    script: sbt ci-release
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
env:
  global:
  - secure: YViDdb5L8s1RcouJPXPcNDJ596kxEnnWnbsQrQbZpeLsPpzKSlx5okzaANFGLnAQz5WOJwuqmmnVqcYIur8ZiecjYkEe4ZcpQef+QEJPz01aWeo9IH05pl6I2uWjLmTnb2mBuI03u4GeLSYX05rd659v9UNokBZtDbwdD8FMPbZq0tCTwVDcZRAK2A+BJO6eKG1YoMOnVEI32krSHw6nLsDLExOtzNnJ4BRbVM5H43lJsRZzXkk8TJZWsJDeLcYPDrGMHD+v5rNprQdhXUQl+FcawR6Tw8fybbVlwvvKw7k9IHBN48QDNbouVy75T7kLp59O4wBQOwpITDeIJhfna2cg+guQvLJ+4FuvTAQ3vyUK3dvf3iF7Njtm+WjQCaqLUf0fRBkFei5pK/JrhIZU41EcaOLHXANBy6GMYQganX3ocRogU3uTLvMKSG4AriZIa0nOFM44gK3x1a4I2aJYrBK6nKyRtKOuDpY2B9enQunCa4y8EFqKN9OAOYc0x+aeGxprxiMKYAuE0qNtp8S9dhyC1Pt36hab8WHWTQLKTm/nDzNRWF846mcvXz8MnanaNEW5TnG6WbMNIb68hfdhnLv6lmXf5kxReKsrrFggIePdqrFBqFuv2UhXN9Eg6hjT0tYokh3OcGyn6YgjhV8iI2q33USGZRPeE3o7kkUxGyo=
  - secure: TBR5tt4+wyHixLOW7E65RgHWMMA8H76iwuQVLlMDaenXME/tTcKKnJ5ee0NmFBGDEwm0i+JNzKLaCgsvmBFIk6PYWmgjkwhnEXdjuC9neSW2gCAnWZySLpg2RjFlRtakabtQTCRaU0OXt8GIzrkuJuuHrNb8NJp+QhO6AZvcEK3Uq3SoEFu9uHrX4AO3y2Uo1xOzqvpYbSyimaAMY7as+4eWWTUwlbnFdpKh3uLmdIqbpWwi6hvSGdUx8IVFty4ObJekfBoBp5T+4wQpBucvKYzOdUDCeCbFKG6IsbOenf2JaxdNjaZGfmu+/jtihDNgSvrKJT4/uUlSUtbWUHuCeEQ1TQm3VAeV4JQ5FpWTw0F3E5qGVjzLPgPXX2pRZ336TRLBiZgjIUfw6gsOh02RdZ3cTEy/PFC8B+8as6kTVpC4j/wD0zqaFkCYFMrwjp1eRI3e+tjSFXq+IpjcI6x9RslPNAIdH74qgxBmBaPRw/U3CW5ICH2yAVIbibwQTetUgWGQaHUB98/uUHqF0DHq7qSucRI4NjTNZUfvmft6AOStNbolh1UfC4sJ1HKhkxdKGmGAm1NKXXLFgEJ4moIgO6lN4ykBPGdikvJz9SI+MMv0yzLZr4aRqjfByXi/umtzdD0xjiNmq9a/P4XcIvaVFo7u/b1Y78CMoZILIMaK27c=
  - secure: H3vF6GQdy6CzaDCMlKKJdoqA6JLi5VBvaVKz7fusjq8iijm9+Zo9s+AH8xwNEbAv0KRs7OSFp3U8Zi+GEv/2lWUjoL2keJhDhmrZ2QSfF9PDim9RNnSiHTCT3ozvXTNu+CEhZd4wa88RSLlZ+H3FtgTHlqjlEpK79/SvbuUt1B2CvKm2OESgA2ZYscMZb8+HN7nrroJM0jz3v1lrLEf/OtNpvCXvm06U3GnrGJhfq3hHaBJ7k/Pshbr/Uu5rqTf7BPdUo3HClqrnKoTyVWChdITVCqWsjla33lUEmP/q6XQGeLzDDJ3M1mfToP3KFGi8jWxcXqfjM4oz+iYCDhuWJ1ZDqdmD8K46sbySxoqW2GG5GY3texetmm0RErcuhqFTq+gZbkuvRfDGh475efnfv3tHoaHrCRWjcSw9ObrmWFfrBgA5sZhYE5q7lD72btlc6xEwHwpXR9T7tZyxK9Axw85xDQWdUhAWpAkHk+HzDNs6B3PK5ecUuBJ826+XaZYq+FchnQ2OuAncdfCrEYGjHQ6QZ+v6kW4wzkw+6V7cLMbTMrNtmknw03RzVHdji66oHr8+vXCSbw5ACWhVrAIzGaU7KyQxL2X7PRqOofRRYqEJTNL4oDeyKeQiJwjnJJyqHT7JQYNJFSAQN5x5OBysPU35bMQoZuI9LkqZKaEnqII=
