sudo: false
language: scala
jdk:
  - oraclejdk11

scala_version_212: &scala_version_212 "2.12.10"
scala_version_213: &scala_version_213 "2.13.1"

before_install:
  - git fetch --tags
stages:
  - name: test
  - name: release
    if: "((branch = master AND type = push) OR (tag IS present)) AND NOT fork"
jobs:
  include:
    - stage: test
      name: test 2.12
      script: sbt ++$TRAVIS_SCALA_VERSION test
      scala: *scala_version_212
    - stage: test
      name: test 2.13
      script: sbt ++$TRAVIS_SCALA_VERSION test
      scala: *scala_version_213
    - stage: release
      script: sbt ci-release
cache:
  directories:
  - "$HOME/.cache/coursier"
  - "$HOME/.sbt"
before_cache:
- find $HOME/.sbt -name "*.lock" -print -delete
env:
  global:
  - secure: nkslqSVrIKApJ8mjIXGZkIHt11yUBlNG3Enek1fvH70UAmBEtLRTbKv2DUdUR32B4FFKibhrnzv9R2bDfpyLM5iErYhuULqE78Hi2DWsdaSELicKIhhhb2S/1keV0AXZ8WqwsqHBtZ3cnpAuWLlr0+HS+TLbT27dj21Z8VSfz5YZEjiPZ2AC8gWUnHKOu4kc/89QRF5glzEWBj2ib+ArSqsa3U5u2lsmoipjtIHSf2xBa5H9pAYwgGrqzp+JHn9io/knDVCtsBHlhZg4jGhXxm/wgBpY77ye6UVHb1KiEc8DRD20h5iecXcPyEpA8vogIEYT9ytX5Wb/rcB0pMmP06Ff0T1aMAuVzKpkbtVg588rdznSkwjzIFQAxtBNiGujM4Ea2b6IHVI4C9x2dmJIJ5uHtUvLyzb+uZ1uHFYmIiUsmhrNCpixNb7ABbXzTDvKEVDysDlpWkNAfW518d/C7kjiUyIqI/W/1I2rjmTLhEoJrpmFOxIkw1pm8qENgoJBbhIBu4oKdbGz40mTTWjwVlrIw+doaw22AQtidRyjukvnnW0tjccFKRsDxRpAGpzaUaz/Sv4wSRBgU24HAT0FwUICbLjm5DZIq1AMJfPm+p7G/50gOEsP+iVyIBmHgSJfL8o5UFgR2DjoAhOAl2c75Uc1ZcTyrIbiH8IAa7o3omM=
  - secure: n06JOI+mUMijVj1VTJLGq0M2mbLJK2D2KoIvr8y8OcPS8b4+/nEX1WD+gYOUTimPn0rTtFOD7gJPK/lY4aTsMNvwvvfU10EU48H0XO6RKEcePT+i7uU+vrTSVcJSlj9Eg9IPz8AsdZF1HcwAKZwshPOiLJmELjVoTgNsK/OMbxcWcQ6NXMHNJHf2vlvwXSE9D7NcekB0ZXU/FWMmDAg0L5zmW7kbEvlx9rwemzqwhns9P6dZUTE5J4iBPkwsGMYgECLY0sOtewhylTy0RkZOhmmPNStwm/ZPg9MGOnZ0B8HH5qr+4SEoTEJZutPgvv4icZyXcgvHOtBZURxSth0Vu8OQbV/sskzmsnPYCIChK6/fQ4Yi/Tnf8ck65Y3ETj6bII8sLXJtv5WmsbQrCfo52SumbP0Q+CKz0aV24nRJKwWXMFzGsX5+67LYiD+cq1UvH9hm3KeGuHap9UjWU0mxZpDTyUqCH7Q91AfJuC3xsRRT7HX9kppHloGi4xl53u3NmeGATQCM1oySUovvLq5NP5eN2A0ljcy5v7o8YXg13HIvKVdFVzHX7agfmyWzMxy53LokcCvWKjdLMm/F44kYPBET4odteD9ov0BMIuoN9PjXqGactZofSx8/Vlg55a6O0TeF7RMUzunrI65oPmo3uH82GbnszWkn//01PiaHHcs=
  - secure: mLO2K7/U/8IhhMsb4fmAxLuvFnHstDvwCiNbqbEBzxzbqjOVKi9hZImCAlDsQJWPQKBi6cNjjqxMqAWiepu9YhkKwYXXUQGUFmZOSEZNiJ15inz/DWZEXleK1g4nPXnmDCPw9Z8pfoua/PgC6B/7PI/BAX9KrhaU729f+2CE/iI/XmQnurZLG+5cbvjKjLNv4LCwiUntmmFERxI8H+OpRzTaamcvbB7gy7SYPlvkN6oks9+AmBekne4Sj/b9G/vtM7GTr56KVZKyJPBDhcshFZO7osNHy+9vC5KnbGVB7CDc79D2CV2Y2kA76zhRH/on3WmcnvIhYBrNvOYQiCxLshY/vKyQRBoljqre/jpi7BHXSSxsQ5z34vdyfmcU9KJhk4bbKFljuQ5nFZtVUyUlQlL2cEAHXm/dnCV7N0cyp+3Bof8O2upJM6AQZENPXEuxJyhjMKxS3PmzqDnPKwmcdv9BdHSfr0Fs4LbXdrA57dI4d8AC5CZLGPnA/4CSSlvpcInWePWNf/1g9qZmJ6xGXUO8KB8zDO5pMlSAhZb17030u1xoVNrsu6D6q5uEsT4/K018Gg3kiswXNx5IZOwpcps10P71y0wcAMhMS5WJh3CTwy0QowkZpu9l4WDkxZI8vz21xhCwEUw472WQaVPed4jSRvwKIFNh2amd7JZnFAY=
