sudo: false
language: scala
scala:
- 2.12.10
jdk:
- openjdk11
before_install:
- git fetch --tags
stages:
- name: test
- name: release
  if: "((branch = master AND type = push) OR (tag IS present)) AND NOT fork"
jobs:
  include:
  - stage: test
    script: sbt test
  - stage: release
    script: sbt ci-release
cache:
  directories:
  - "$HOME/.cache/coursier"
  - "$HOME/.sbt"
before_cache:
- find $HOME/.sbt -name "*.lock" -print -delete
env:
  global:
  - secure: bv6Jr52LL9HOkx5+EkBuJdR5QDsWv3cUrmpoA2CtfjR7wKgUD+b+hvxPoPFppRBbcI5Wa8pjKHh9h09FPDcyzjl7u25woey9dD1wEP1SC7EEUdV3ra8rkiXVc1IaWVUBj2H3FpdZ8AnktP97WPdnZv8ryAbx8+vCDr7hr5YCP1DiUrQeOkGaPMecO/6sRM9yJqOkgD+KLBpb3sheygXHcJPlzBX64JhwJNO8Wotx50yirFgQsWZg2NZyUVWwiiqzRZna9zpNbEtzzIwLmQBUZ1vBeg8lBE6etHvah73tqPHl775VcM08Lku+oLPz3v4GhC7XFgwhoJXSh18ZIGkT76Kiq9FQcqkkXxhmAQ7W8gexjBTFLkbXZB2vHd8sI5bHZ0IsKKZqoPmQDRcm0kEjpO+4y9Fja4BG2JpbMEs5aCVJ7f9mfGA40UbpOCpJcxLl1pWxjJ+DlwTe/DQvqADmRUm0S9U2fbBX3WzMjgU+ZE5o8BmWc9jCzfWBvDFd5XBY0MYn/TXiUL3barAjClviZ6feoWXXHbCuse02aBEIhwufJTK6J0ZC7tsd7ecm3FLsr/c8HffTneUMHNHeWirwKOltZ9oHlgrrZ8jP569/2vGwdWRC1zE8RmOkKTubSzzSKk384hZaT/mQDgIAUY+1hVPO2XyhH0jGHXVdCAJLN+g=
  - secure: DAkyfKmP6ie2wv9JXvHVXQgw52LjYlu2i3qScp7fTbT9mOkzTYd1fMksM2bI+qCNRsSZ4DvlfPntmcLoamTMdIMjstbqcs3DSsWA+QJxM4JF+wPNcXJN63Rm0StmFysQI1ygDLZc39HoJUHiDCpaiMbpQO+l8EMkNhPJrzp1Wbi47gNY+Fo9etnlsQTrX2tfnyAxglTeKTJ1rEjMwqtcItcHJUGHA4tzOQDdAEyWEagkjejyFJfmu73gOwZoIipopHdCJgWiiG0Hb2BPcu0DlQBLv5Ms2KB/lSWPkkwLl9Fz4+kJYeP+U1ywQiINVdUEQq3yiu6Gg5R7r1AzXeC5EjhqNtQc5GwfkMUDtueMAZZ1CbWuCGhe6JqmZU3OIhBP9PfbJUoubDr3RYjuvCDKxCIrwIDtOCn7mWzId9cmPwzPJzR50TaBcs9xh8gRXHZN8ukbE19lMW5+BnBxAozCoQbrOZlL14OEcU6yR6Oh41EQFZxY2yzHiAy7easczADSzimq+OqPT2JsZrQZZJ5OeT8rcdSpPX0XX+znrs09B8B4appiCLjZQJQIwX98cG8l5+/wzSx9YwGWLg9K5RSLLrzGM14hSzae1N/DTq8prakXh39WBd8cMF+q9uEw12BhnFLfl+tKOK32Fy+zaDV2z+DA3dDgLNlLQOnSE6RRDBg=
  - secure: Q/UzXVUV/OA0qRbqndNguQGj5IlZw4hUL9c7tIGEFE3pQD4Famjw97EzPrDTtH4pZTQDvDChxJlrhOXZ45yjn9p025ZyxkOB7DaFaU+IxkE2WOaMoqeyBl4N0c1a2iRCPBk65dx7XowL7e3+jNGtefnDct0ePse1ygSgkW2VfF2vTIJgs1rxlhw072fmIvNlcc1fUwfXBuFgkJ1sw3ckHtPVgr7Hre5WTxMZA3YCMevvZrGosMxJbW9VHXzF3EOfsI5L0yAj2NBEkjJdSBOFwV1PlCCpnSJDbCRNtpviTL2hpUF5JjkBgW8MHDBNoaLBnBrxoQ6B0XyuAg1bND+QpPt6uHx4jM+8jRiVx29EsPM8LGPlAMteRqCbFlTPIyed6ft9ew1oS9GwpM0NqWe8xtG6aFqCsi46ciAr3xfKHnf5IxHp8iKx3Y8DQgRmZWIy2A+adJ2NjBUU2JTfkRQGcgc21CMHrmIK+biD5nCVTY83lnoxGnJm6OWvhZqeDBzI5V7nSU4FbNIDVbbAoV1ukaZPvGHEzvxC8+HrJ8Ma8A4PoiR+NoOimxt+7vtm1HtY3w633pYEVbjd7x24ZImWwXTytGTxkCiKyAwSSmMSBhDHEMhfzOcMfSvhs2MiRHJ5NWw/Su+SMCGDjpLtoElBU9P/G/W1EzXPCGSZKJs362k=
